spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URLjdbc:postgresql://postgres:5432/ecommerce}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: fasle
      hibernate.format_sql: true

# Logging para desarrollo
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE