server:
  port: ${PORT:8080}

spring:
  application:
    name: ecommerce
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: never

# Logging general
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Variables comunes JWT / S2S
app:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_ACCESS_EXPIRATION:900000} # 15 min
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 días
  s2s:
    secret: ${S2S_SECRET}
payments:
  approval-rate: 0.5

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}