spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:ecommerce_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
app:
  jwt:
    secret: test-secret
    access-expiration: 60000
    refresh-expiration: 120000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.blossom: DEBUG
    org.hibernate.SQL: WARN