server:
  port: ${PORT:8080}

spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbit}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    stream:
      host: ${RABBITMQ_HOST:rabbit}
      port: ${RABBITMQ_STREAM_PORT:5552}
      username: ${RABBITMQ_USER:guest}
      password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/ecommerce}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: false

# Logging controlado
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN